[package]
name = "aoc15-13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
aoc_common = { path ="../../common" }
itertools = "0.10.3"
